### Create an issue
POST http://localhost:3001/api/issues
Content-Type: application/json

{
  "title": "Dummy Issue",
  "description": "Dummy description"
}


### Edit an issue
PATCH http://localhost:3001/api/issues/1
Content-Type: application/json

{
  "title": "Dummy Issue edited",
  "description": "Dummy issue description edited"
}

### Delete an issue
DELETE http://localhost:3001/api/issues/1
