import { Inter } from "next/font/google"
import type { Metadata } from "next"
import React from "react"

import { Providers } from "@/app/context/providers"
import NavBar from "@/app/NavBar"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
      <Providers>
        <NavBar />
        <main>{children}</main>
      </Providers>
      </body>
    </html>
  )
}
